
# autogenerated by regex.py
import re

find_all_scriptures = re.compile("""
(
(?P<genesis>gen\w{0,4}\.?) # genesis           
|(?P<expandables>exp\w{0,8}\.?) # expandables            
|(?P<annabelle>ann\w{0,6}\.?) # annabelle         
|(?P<lucy>luc\w{0,1}\.?) # lucy           
|(?P<titanic>tit\w{0,4}\.?) # titanic       
|(?P<journey>jou\w{0,4}\.?) # journey          
|(?P<judge>judg\w{0,1}\.?) # judge           
|(?P<spiderman>spi\w{0,6}\.?) # spiderman              
|(?P<avengers>ave\w{0,5}\.?) # avengers              
|(?P<nemo>nem\w{0,1}\.?) # nemo          
|(?P<hollywood>hol\w{0,6}\.?) # hollywood            
|(?P<joy>jo\w{0,1}\.?) # joy              
|(?P<prince>pri\w{0,3}\.?) # prince             
|(?P<teenage>tee\w{0,4}\.?) # teenage          
|(?P<hercules>her\w{0,5}\.?) # hercules      
|(?P<apes>ape[\w\s]{0,1}\.?) # apes   
|(?P<transformers>tra\w{0,12}\.?) # transformers            
|(?P<jeremiah>jer\w{0,5}\.?) # jeremiah          
|(?P<bollywood>bol\w{0,6}\.?) # bollywood             
|(?P<cruise>cru\w{0,3}\.?) # cruise              
|(?P<revenge>rev\w{0,4}\.?) # revenge        
)
\s+(?P<verse>\d{1,3}\s*:\s*\d{1,3})
""",re.VERBOSE|re.MULTILINE).finditer

def filtergroupdict(ma):
    """Remove all entries with values == None"""
    di = filter(lambda x: x[1]!=None and x[0]!='verse', ma.groupdict().items())

    if len(di) != 1:
        return None

    ret = {}
    ret['book'] = di[0][0]
    ret['verse'] = ma.groupdict()['verse']
    ret['verse'] = ret['verse'].replace(' ','')
    return ret

